### ISSUE TITLE
Q71についての問題文の回答について

### ISSUE THREAD

**Issue by Raiu1210** [kunishou/Pandas_100_knocks#1]
初めまして、pandas100本ノックで勉強させていただいております。

Q. 71：df2においてclassでグルーピングし、クラスごとの科目の最大値、最小値、平均値を求める(name列は削除しておく)

との問題についての回答が

```
df2 =df2.drop('name',axis=1)
print(df2.groupby('class').max())
print(df2.groupby('class').min())
print(df2.groupby('class').median())
```

となっておりますが、平均値であればmedian()ではなくmean()ではないかなと思ったのですが、こちらは誤植でありますでしょうか？

細かい指摘ではありますがご報告させていただきました。

**Comment by kunishou** [comment]
Raiu1210様

返信が遅くなりました。おっしゃる通り、Q71の回答はmedian()ではなくmean()が正しいため、コードのほう修正したいと思います。ご指摘いただき誠にありがとうございます。
