### ISSUE TITLE
Q8. 文字型変換について

### ISSUE THREAD

**Issue by hodagi** [kunishou/Pandas_100_knocks#2]
初めまして、pandas100本ノックで勉強させていただいております。

Q8において、dfのpclassの列のデータ型を数値型から文字型に型変換する問題が出てきますが、
pandasのユーザーガイドに記載されていた方法と回答&出力結果が違ってたので認識があってるか
確認させてください。
https://pandas.pydata.org/docs/user_guide/text.html

```py
>>> print(pd.__version__)
1.5.2
>>> print(df['pclass'].astype(str).dtype)
object
>>> print(df['pclass'].astype("unicode").dtype)
object
>>> print(df['pclass'].astype("string").dtype)
string
```

1. 回答にある `df['pclass'].astype(str).dtype` は `str` というデータ型を指定
→pandasで解釈できないので 汎用的な？ `object` に変換

2. "string" というデータ型を指定
→文字列型に変換

3. `unicode` というデータ型を指定
→ `Unicode string` という型に変換してほしいが...

お手数をおかけして恐縮ですが、今の書き方とか内部ではこういう挙動になってるんだよーとか補足があれば
是非ご教授お願い致します。

**Comment by kunishou** [comment]
コメントありがとうございます。pandasのテキストデータ保持方法には2通りあり、objectとして保持する方法とpandas 1.0以降に追加されたStringDtypeで保持する方法がありますが、pandas100本ノックの回答は前者のobjectで保持する場合の方法になっております。よろしくお願いします。

【参考】
https://qiita.com/nkay/items/3866b3f12704ec3271ca
https://note.nkmk.me/python-pandas-dtype-astype/

**Comment by hodagi** [comment]
ご回答ありがとうございます！
