### ISSUE TITLE
ソースコードのままの状態の共有について

### ISSUE THREAD

**Issue by bilzard** [kunishou/Pandas_100_knocks#3]
こんにちは。

ソースコードをZipファイルで提供していますが、特に理由がなければソースコードのまま共有した方が利便性が高いのではと思いました。GitHubはZIPでのダウンロードに対応しているので、アーカイブファイルをアップロードしなくても未解凍の状態で展開できます。

<img width="523" alt="Screen Shot 2023-01-12 at 16 19 49" src="https://user-images.githubusercontent.com/36561962/212003645-62a47c12-3d2e-438a-abda-c7c38edb626c.png">

**Comment by kunishou** [comment]
コメントいただきありがとうございます。おっしゃる通りかと思いますのでソースコードで共有する方法に変更いたしました（はじめてGithubを使ったときに作成したリポジトリで、良く分からずZIPであげていたものをそのままにしておりました）。ご指摘いただきありがとうございます。

**Comment by bilzard** [comment]
見やすくなりました。対応ありがとうございます。
